sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36-django22
    - python: '3.7'
      env: TOXENV=py37-django22
    - python: '3.8'
      env: TOXENV=py38-django22
    - python: '3.9'
      env: TOXENV=py39-django22

    - python: '3.6'
      env: TOXENV=py36-django30
    - python: '3.7'
      env: TOXENV=py37-django30
    - python: '3.8'
      env: TOXENV=py38-django30
    - python: '3.9'
      env: TOXENV=py39-django30

    - python: '3.6'
      env: TOXENV=py36-django31
    - python: '3.7'
      env: TOXENV=py37-django31
    - python: '3.8'
      env: TOXENV=py38-django31
    - python: '3.9'
      env: TOXENV=py39-django31

    - python: '3.6'
      env: TOXENV=py36-django32
    - python: '3.7'
      env: TOXENV=py37-django32
    - python: '3.8'
      env: TOXENV=py38-django32
    - python: '3.9'
      env: TOXENV=py39-django32
    - python: '3.10'
      env: TOXENV=py310-django32

install:
  - pip install -U pip wheel setuptools
  - pip install tox
script: tox
